%% diag type
classDiagram
direction TB

%% formatting for space constriants 
%%{init: {"layout": "elk", "class": {"hideEmptyMembersBox": true, "nodeSpacing": 25, "rankSpacing": 35, "diagramPadding": 8, "useMaxWidth": true}}}%%

%% classes
class notaktoGame["notaktoGame : NotaktoGame"] {
    Mode = HUMAN_VS_HUMAN
    Result = IN_PROGRESS
    NotaktoGame._boards = [board0, board1, board2]
    NotaktoGame._players = [player1, player2]
    _moveHistory = history
    _currentPlayer = player1
    _inactiveBoards = [0]
    _symbol = X
}

class board0["board0 : Board"] {
    rows = 3
    cols = 3
    cells = [mark1, mark1, mark2, null, null, null, null, null, null]
}
note for board0 "The top row contains X X X, so board 0 is inactive."

class board1["board1 : Board"] {
    rows = 3
    cols = 3
    cells = [null, null, null, null, mark2, null, null, null, null]
}

class board2["board2 : Board"] {
    rows = 3
    cols = 3
    cells = [null, null, null, null, null, null, null, null, null]
}

class player1["player1 : HumanPlayer"] {
    Id = 1
    Name = Player 1
    _availablePieces = [mark1]
}
class player2["player2 : HumanPlayer"] {
    Id = 2
    Name = Player 2
    _availablePieces = [mark2]
}
class mark1["mark1 : MarkPiece"] {
    _symbol = X
}
class mark2["mark2 : MarkPiece"] {
    _symbol = X
}

class history["history : MoveHistory"] {
    moves = [move1, move2, move3, move4]
    currentMoveIndex = 3
}
class move1["move1 : Move"] {
    player = player1
    boardIndex = 0
    row = 0
    column = 0
    piece = mark1
}
class move2["move2 : Move"] {
    player = player2
    boardIndex = 1
    row = 1
    column = 1
    piece = mark2
}
class move3["move3 : Move"] {
    player = player1
    boardIndex = 0
    row = 0
    column = 1
    piece = mark1
}
class move4["move4 : Move"] {
    player = player2
    boardIndex = 0
    row = 0
    column = 2
    piece = mark2
}

%% connections

%% aggregation
notaktoGame o-- board0 : board 0
notaktoGame o-- board1 : board 1
notaktoGame o-- board2 : board 2
notaktoGame o-- player1 : current player
notaktoGame o-- player2 : player 2
notaktoGame *-- history : history


player1 o-- mark1 : reusable mark
player2 o-- mark2 : reusable mark

board0 o-- mark1 : cells 0 and 1

board0 o-- mark2 : cell 2
board1 o-- mark2 : cell 4

history o-- move1 : first
history o-- move2 : second
history o-- move3 : third
history o-- move4 : fourth

%% association
move1 --> player1 : player
move1 --> mark1 : piece
move2 --> player2 : player
move2 --> mark2 : piece
move3 --> player1 : player
move3 --> mark1 : piece
move4 --> player2 : player
move4 --> mark2 : piece
